### ISSUE TITLE
App controls door

### ISSUE THREAD

**Issue by CHeffernan087** [CHeffernan087/Smart_Latch#7]
<s>
Integrate parts from Epic 1. This could be an issue but will require a lot of collaboration so I made it an epic. New flow should go: 

- [x] click button signals chip to start polling the backend "/openDoor" endpoint. The response from the server will continually be "wait 1 second"
- [ ] now press button in app. This will log a request at the backend for the client to enter
- [ ] Result from "/openDoor" should now return "ok"
- [ ] The servo should now open the door

</s>

Updating to reflect new state of the system:

- [ ] camera communicates with esp32 to open websocket connection 
- [x] Migrate backend to google cloud functions and google compute engine
- [x] user taps button on phone to send signal to cloud function, cloud function signals google compute engine which talks to board along web socket connection 
- [x] on receiving appropriate message, the esp32 should close the websocket connnection and turn the servo to open the door
